# Generated by Django 5.1.7 on 2025-09-27 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, help_text='Optional first name of the user.', max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text='Optional last name of the user.', max_length=150, verbose_name='last name')),
                ('country_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='country code')),
                ('phone_number', models.CharField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, max_length=18, null=True, unique=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, error_messages={'invalid': 'Invalid email address.', 'unique': 'A user with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='email')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='profile picture')),
                ('google_id', models.CharField(blank=True, error_messages={'unique': 'A user with that Google ID already exists.'}, max_length=255, null=True, unique=True, verbose_name='google id')),
                ('facebook_id', models.CharField(blank=True, error_messages={'unique': 'A user with that Facebook ID already exists.'}, max_length=255, null=True, unique=True, verbose_name='facebook id')),
                ('email_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.', verbose_name='email verified')),
                ('phone_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their phone number.', verbose_name='phone verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='One-time password code for verification', max_length=6, verbose_name='OTP code')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration time for the OTP code', null=True, verbose_name='expires at')),
                ('user', models.ForeignKey(help_text='The user associated with this OTP', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(help_text='Primary address line', max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Secondary address line (optional)', max_length=255, null=True, verbose_name='address line 2')),
                ('city', models.CharField(help_text='City of the address', max_length=100, verbose_name='city')),
                ('state', models.CharField(help_text='State or province of the address', max_length=100, verbose_name='state')),
                ('postal_code', models.CharField(help_text='Postal or ZIP code of the address', max_length=20, verbose_name='postal code')),
                ('country', models.CharField(help_text='Country of the address', max_length=100, verbose_name='country')),
                ('is_default', models.BooleanField(default=False, help_text='Designates whether this address is the default for the user', verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(help_text='The user associated with this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user address',
                'verbose_name_plural': 'user addresses',
                'ordering': ['-created_at'],
            },
        ),
    ]
