# Generated by Django 5.1.7 on 2025-09-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this address is the default for the user', verbose_name='is default'),
        ),
    ]
