# Generated by Django 5.1.7 on 2026-01-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this address is active', verbose_name='is active'),
        ),
    ]
