# Generated by Django 5.1.7 on 2026-08-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraddress_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Account created silently during guest checkout. It has no usable password, so guest checkout may sign it in from an email/phone alone. Clears once the customer sets a password.', verbose_name='guest account'),
        ),
    ]
