# Generated by Django 5.1.7 on 2026-09-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, help_text='How many wrong codes have been submitted against this OTP', verbose_name='failed attempts'),
        ),
        migrations.AddField(
            model_name='otp',
            name='send_count',
            field=models.PositiveIntegerField(default=1, help_text='How many codes have been issued to this user in the current cycle', verbose_name='send count'),
        ),
    ]
