# Generated by Django 5.1.7 on 2026-09-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otp_attempt_count_otp_send_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=10, verbose_name='phone number')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('verify', 'Phone verification')], max_length=10, verbose_name='purpose')),
                ('code_hash', models.CharField(max_length=64, verbose_name='code hash')),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='requested from')),
                ('wa_message_id', models.CharField(blank=True, max_length=128, verbose_name='WhatsApp message id')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='failed attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
            ],
            options={
                'verbose_name': 'phone OTP',
                'verbose_name_plural': 'phone OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
