# Generated by Django 5.1.7 on 2026-09-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('verify', 'Phone verification'), ('reset', 'Password reset')], max_length=10, verbose_name='purpose'),
        ),
    ]
