# Generated by Django 5.1.7 on 2026-02-08 22:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_productreviewmedia_alter_productreview_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('batch_number', models.CharField(help_text='Enter the batch number for this lab report', max_length=100, verbose_name='batch number')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('report_file', models.FileField(help_text='Upload the lab report file', upload_to='lab_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx'])], verbose_name='report file')),
                ('report_date', models.DateField(help_text='Enter the date of the lab report', verbose_name='report date')),
                ('qr_code', models.ImageField(blank=True, editable=False, null=True, upload_to='lab_report_qr_codes/', verbose_name='QR code')),
                ('product', models.ForeignKey(help_text='Select the product for this lab report', on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'lab report',
                'verbose_name_plural': 'lab reports',
                'ordering': ['-report_date'],
                'constraints': [models.UniqueConstraint(fields=('product', 'batch_number'), name='unique_batch_per_product')],
            },
        ),
    ]
