# Generated by Django 5.1.7 on 2025-09-30 19:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Coupon ID')),
                ('coupon_code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Coupon Code')),
                ('discount_type', models.CharField(choices=[('amount', 'Fixed Amount'), ('percent', 'Percentage'), ('shipping', 'Free Shipping')], default='amount', help_text='Type of discount', max_length=20, verbose_name='Discount Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed discount amount', max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Fixed Amount')),
                ('percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percentage')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Coupon valid from this date', verbose_name='Start Date')),
                ('minimum_cart_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount for this coupon to be valid', max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Minimum Cart Amount')),
                ('end_date', models.DateField(blank=True, help_text='Coupon valid until this date (optional)', null=True, verbose_name='End Date')),
                ('max_use', models.PositiveIntegerField(default=1, help_text='Maximum number of times this coupon can be used', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Uses')),
                ('used', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used', verbose_name='Times Used')),
                ('uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum number of times a user can use this coupon', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Uses Per User')),
                ('free_shipping', models.BooleanField(default=False, help_text='If true, delivery charges are waived', verbose_name='Free Shipping')),
                ('status', models.BooleanField(default=True, help_text='Whether this coupon is currently active', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupon',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='coupon_start_d_eb7b0c_idx'), models.Index(fields=['status'], name='coupon_status_94fe71_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Times Used by User')),
                ('first_used_at', models.DateTimeField(auto_now_add=True, verbose_name='First Used At')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Last Used At')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='coupon.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'db_table': 'coupon_usage',
                'indexes': [models.Index(fields=['coupon', 'user'], name='coupon_usag_coupon__5e60eb_idx')],
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
