# Generated by Django 5.1.7 on 2026-06-20 21:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Coupon Code')),
                ('discount_type', models.CharField(choices=[('amount', 'Fixed Amount'), ('percent', 'Percentage'), ('shipping', 'Free Shipping')], default='amount', max_length=20, verbose_name='Discount Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Fixed Amount')),
                ('percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percentage')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Free Shipping')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_coupons', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Temporary Coupon',
                'verbose_name_plural': 'Temporary Coupons',
                'db_table': 'temp_coupon',
            },
        ),
        migrations.CreateModel(
            name='UserSpinLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_spin_date', models.DateField(blank=True, null=True, verbose_name='Last Spin Date')),
                ('allowed_by_admin', models.BooleanField(default=False, help_text='If True, allows user to spin again on the same day', verbose_name='Allowed By Admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spin_limit', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Spin Limit',
                'verbose_name_plural': 'User Spin Limits',
                'db_table': 'user_spin_limit',
            },
        ),
    ]
