# Generated by Django 5.1.7 on 2026-06-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_tempcoupon_userspinlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspinlimit',
            name='spin_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the user has spun today', verbose_name='Spin Count'),
        ),
    ]
