# Generated by Django 5.1.7 on 2025-09-29 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, help_text='Enter the product name', max_length=255, null=True, verbose_name='product name')),
                ('details', models.CharField(blank=True, help_text='Enter the product details', max_length=255, null=True, verbose_name='product details')),
                ('description', models.TextField(blank=True, help_text='Enter the product description', null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the product price', max_digits=10, verbose_name='price')),
                ('max_quantity', models.PositiveIntegerField(default=25, help_text='Enter the maximum quantity available for the product', verbose_name='maximum quantity')),
                ('available_quantity', models.PositiveIntegerField(help_text='Enter the available quantity for the product', verbose_name='available quantity')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this product should be treated as active', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='product_pro_name_b60cd1_idx'), models.Index(fields=['created_at'], name='product_pro_created_57e07a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a product image', upload_to='products/%Y/%m/%d/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for image accessibility', max_length=255, verbose_name='alternative text')),
                ('is_feature', models.BooleanField(default=False, help_text='Set this image as a feature image', verbose_name='feature image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['-created_at'],
            },
        ),
    ]
