# Generated by Django 5.1.7 on 2025-12-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(db_index=True, help_text='Enter the category name', max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, help_text='Enter the category description', verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select the category for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='category'),
        ),
    ]
