# Generated by Django 5.1.7 on 2026-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_discount_precent_product_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active'),
        ),
    ]
