# Generated by Django 5.1.7 on 2026-01-10 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_is_active_productreview_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('feature', models.CharField(help_text='Enter the feature name', max_length=100, verbose_name='feature name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product feature',
                'verbose_name_plural': 'product features',
                'ordering': ['feature'],
            },
        ),
    ]
