# Generated by Django 5.1.7 on 2026-01-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('500g', '500 grams'), ('1kg', '1 kilogram')], help_text='Enter the product size', max_length=50, verbose_name='size'),
        ),
    ]
