# Generated by Django 5.1.7 on 2026-02-08 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_details_alter_product_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='product_reviews/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'webm'])])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'product review media',
                'verbose_name_plural': 'product review media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Enter a rating between 1 and 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'created_at'], name='product_pro_product_d57102_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user'], name='product_pro_user_id_270cc2_idx'),
        ),
        migrations.AddField(
            model_name='productreviewmedia',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.productreview', verbose_name='product review'),
        ),
        migrations.AddIndex(
            model_name='productreviewmedia',
            index=models.Index(fields=['review', 'media_type'], name='product_pro_review__414947_idx'),
        ),
    ]
