# Generated by Django 4.2.16 on 2025-08-28 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the notification', max_length=255, verbose_name='Notification Title')),
                ('message', models.TextField(help_text='Enter the message of the notification', verbose_name='Notification Message')),
                ('is_read', models.BooleanField(default=False, help_text='Check this box if the notification has been read', verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the notification was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the notification was last updated', verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='Select the user for this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
