# Generated by Django 5.1.7 on 2025-09-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='SMTP server hostname', max_length=255, verbose_name='SMTP Host')),
                ('port', models.IntegerField(help_text='SMTP server port number', verbose_name='SMTP Port')),
                ('username', models.CharField(help_text='SMTP authentication username', max_length=255, verbose_name='SMTP Username')),
                ('password', models.CharField(help_text='SMTP authentication password', max_length=255, verbose_name='SMTP Password')),
                ('from_email', models.EmailField(help_text='Default sender email address', max_length=254, verbose_name='From Email')),
                ('use_tls', models.BooleanField(default=True, help_text='Enable TLS encryption for SMTP connection', verbose_name='Use TLS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
