# Generated by Django 5.1.7 on 2026-09-05 21:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_handling_fee', models.DecimalField(decimal_places=2, default=Decimal('49.00'), help_text='Added to the total when the shopper chooses Cash on Delivery. Set 0 to charge nothing for COD.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='COD handling fee')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Flat delivery charge on orders below the free shipping threshold.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='shipping fee')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('599.00'), help_text='Orders with a subtotal above this ship free. The public Shipping Policy page quotes this figure — update the page to match.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='free shipping above')),
                ('prepaid_discount_enabled', models.BooleanField(default=False, help_text='On: paying online takes the discount below off the total, and COD is charged no handling fee. Off: COD pays the handling fee above and paying online gets nothing. The gap the shopper sees is the same either way — a discount simply persuades more of them.', verbose_name='reward prepaid instead of charging COD')),
                ('prepaid_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taken off the total when the shopper pays online. Ignored while the switch above is off.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prepaid discount')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Pricing Settings',
                'verbose_name_plural': 'Pricing Settings',
            },
        ),
    ]
