# Generated by Django 5.1.7 on 2026-01-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('address_line1', models.CharField(help_text='Enter the first line of the address', max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Enter the second line of the address (optional)', max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(help_text='Enter the city', max_length=100, verbose_name='city')),
                ('state', models.CharField(help_text='Enter the state or province', max_length=100, verbose_name='state')),
                ('postal_code', models.CharField(help_text='Enter the postal or ZIP code', max_length=20, verbose_name='postal code')),
                ('country', models.CharField(help_text='Enter the country', max_length=100, verbose_name='country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('email', models.EmailField(help_text='Enter the email address', max_length=255, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('question', models.TextField(help_text='Enter the frequently asked question', verbose_name='question')),
                ('answer', models.TextField(help_text='Enter the answer to the frequently asked question', verbose_name='answer')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('phone_number', models.CharField(help_text='Enter the phone number', max_length=20, unique=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SendUsQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=255, verbose_name='last name')),
                ('email', models.EmailField(help_text='Enter your email address', max_length=255, verbose_name='email')),
                ('phone_number', models.CharField(help_text='Enter your contact number', max_length=20, verbose_name='contact number')),
                ('subject', models.CharField(help_text='Enter the subject of your query', max_length=255, verbose_name='subject')),
                ('message', models.TextField(help_text='Enter your message or query', verbose_name='message')),
            ],
            options={
                'verbose_name': 'Send Us Query',
                'verbose_name_plural': 'Send Us Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
