# Generated by Django 5.1.7 on 2026-01-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('platform_name', models.CharField(help_text='Enter the name of the social media platform', max_length=100, verbose_name='platform name')),
                ('url', models.URLField(help_text='Enter the URL of the social media profile', max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
