# Generated by Django 5.1.7 on 2026-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='email',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='faqs',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='sendusquery',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active'),
        ),
    ]
