# Generated by Django 5.1.7 on 2026-01-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_address_is_active_email_is_active_faqs_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform_name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], help_text='Enter the name of the social media platform', max_length=100, verbose_name='platform name'),
        ),
    ]
