# Generated by Django 5.1.7 on 2026-02-23 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_socialmedialink_platform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(help_text='Enter the name of the FAQ category', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text='Enter a unique slug for the FAQ category', max_length=255, unique=True, verbose_name='slug')),
                ('order', models.PositiveIntegerField(default=0, help_text='Enter the display order for the FAQ category', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the FAQ category is active', verbose_name='is active')),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'ordering': ['order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='faqs',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Enter the display order for this FAQ', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this FAQ is active', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='faqs',
            name='category',
            field=models.ForeignKey(help_text='Select the category for this FAQ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='contact.faqcategory', verbose_name='category'),
        ),
    ]
