# Generated by Django 5.1.7 on 2026-02-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_faqcategory_alter_faqs_options_faqs_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('email', models.EmailField(help_text='Enter the email address to subscribe', max_length=255, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
