# Generated by Django 5.1.7 on 2026-02-23 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(help_text='Enter the blog category name', max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug from the category name', max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(help_text='Enter the blog title', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug from the blog title', max_length=255, unique=True, verbose_name='slug')),
                ('excerpt', models.TextField(help_text='Enter a short excerpt for the blog', verbose_name='excerpt')),
                ('content', models.TextField(help_text='Enter the blog content', verbose_name='content')),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload a thumbnail image for the blog', null=True, upload_to='blog_thumbnails/', verbose_name='thumbnail')),
                ('is_featured', models.BooleanField(default=False, help_text='Indicates whether this blog is featured', verbose_name='is featured')),
                ('read_time', models.CharField(help_text='Enter the estimated read time for the blog (e.g., "5 min read")', max_length=50, verbose_name='read time')),
                ('meta_title', models.CharField(help_text='Enter the meta title for SEO purposes', max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(help_text='Enter the meta description for SEO purposes', verbose_name='meta description')),
                ('category', models.ForeignKey(help_text='Select the category for this blog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blogs.blogcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
