# Generated by Django 5.1.7 on 2025-09-30 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('phonepe', 'PhonePe'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], default='phonepe', max_length=20, verbose_name='Payment Method')),
                ('payment_instrument_type', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('PAY_PAGE', 'Pay Page')], help_text='Type of payment instrument used', max_length=20, null=True, verbose_name='Payment Instrument Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Transaction status', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(help_text='PhonePe transaction reference', max_length=255, unique=True, verbose_name='Transaction ID')),
                ('merchant_transaction_id', models.CharField(help_text='Our internal transaction reference', max_length=255, unique=True, verbose_name='Merchant Transaction ID')),
                ('phonepe_transaction_id', models.CharField(blank=True, help_text='PhonePe internal transaction ID', max_length=255, null=True, verbose_name='PhonePe Transaction ID')),
                ('payment_details', models.JSONField(default=dict, help_text='Additional PhonePe response details', verbose_name='Payment Details')),
                ('response_code', models.CharField(blank=True, help_text='PhonePe response code', max_length=50, null=True, verbose_name='Response Code')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID used for payment', max_length=255, null=True, verbose_name='UPI ID')),
                ('card_type', models.CharField(blank=True, help_text='Type of card used (DEBIT/CREDIT)', max_length=50, null=True, verbose_name='Card Type')),
                ('card_network', models.CharField(blank=True, help_text='Card network (VISA, MASTERCARD, etc.)', max_length=50, null=True, verbose_name='Card Network')),
                ('bank_name', models.CharField(blank=True, help_text='Bank used for payment', max_length=255, null=True, verbose_name='Bank Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='transaction_transac_789701_idx'), models.Index(fields=['merchant_transaction_id'], name='transaction_merchan_6a5989_idx'), models.Index(fields=['payment_method'], name='transaction_payment_a8c66a_idx'), models.Index(fields=['status'], name='transaction_status_45ce62_idx'), models.Index(fields=['user', 'status'], name='transaction_user_id_bf609c_idx')],
            },
        ),
    ]
