# Generated by Django 5.1.7 on 2025-12-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='auth_id',
            field=models.CharField(blank=True, help_text='Payment gateway authorization ID', max_length=255, null=True, verbose_name='Auth ID'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='bank_reference',
            field=models.CharField(blank=True, help_text='Bank reference number', max_length=255, null=True, verbose_name='Bank Reference'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='cashfree_order_id',
            field=models.CharField(blank=True, help_text='Cashfree internal order ID (cf_order_id)', max_length=255, null=True, verbose_name='Cashfree Order ID'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='order_token',
            field=models.TextField(blank=True, help_text='Cashfree order token for SDK integration', null=True, verbose_name='Order Token'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='payment_group',
            field=models.CharField(blank=True, help_text='Payment group (credit_card, upi, net_banking, etc.)', max_length=50, null=True, verbose_name='Payment Group'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='payment_session_id',
            field=models.CharField(blank=True, help_text='Cashfree payment session ID', max_length=255, null=True, verbose_name='Payment Session ID'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='payment_method',
            field=models.CharField(choices=[('phonepe', 'PhonePe'), ('cashfree', 'Cashfree'), ('stripe', 'Stripe'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], default='phonepe', max_length=20, verbose_name='Payment Method'),
        ),
    ]
