# Generated by Django 5.1.7 on 2026-01-15 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_payment_method_order_invoice'),
        ('transactions', '0002_transactionlog_auth_id_transactionlog_bank_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionlog',
            name='transaction_transac_789701_idx',
        ),
        migrations.RemoveIndex(
            model_name='transactionlog',
            name='transaction_merchan_6a5989_idx',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='merchant_transaction_id',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='phonepe_transaction_id',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='gateway_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Payment gateway internal payment ID (PhonePe/Cashfree transaction ID)', max_length=255, null=True, verbose_name='Gateway Payment ID'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Our internal order/transaction reference (e.g., NAV_ORDER_16_xxx)', max_length=255, null=True, unique=True, verbose_name='Transaction Order ID'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, help_text='Complete gateway response for audit trail', verbose_name='Payment Details'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction_order_id'], name='transaction_transac_377d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['gateway_payment_id'], name='transaction_gateway_4ec0be_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['cashfree_order_id'], name='transaction_cashfre_4510c5_idx'),
        ),
    ]
