# Generated by Django 5.1.7 on 2026-03-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transactionlog_transaction_transac_789701_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='payment_method',
            field=models.CharField(choices=[('phonepe', 'PhonePe'), ('cashfree', 'Cashfree'), ('cod', 'Cash on Delivery'), ('stripe', 'Stripe'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], default='phonepe', max_length=20, verbose_name='Payment Method'),
        ),
    ]
