# Generated by Django 5.1.7 on 2026-05-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(help_text='Full Instagram reel/post URL, e.g. https://www.instagram.com/reel/ABC123/')),
                ('thumbnail', models.ImageField(help_text='Thumbnail image for the reel (upload a screenshot or cover image)', upload_to='reels/thumbnails/')),
                ('caption', models.CharField(help_text='Short caption to display below the reel card', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instagram Reel',
                'verbose_name_plural': 'Instagram Reels',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
