# Generated by Django 5.1.7 on 2026-09-29 20:29

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import pathlib
import whatsapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text='Digits only, with country code, as Meta sends it (e.g. 919876543210).', max_length=20, unique=True, verbose_name='WhatsApp number')),
                ('profile_name', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp name')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last message at')),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True, verbose_name='last customer message at')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='unread')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to=settings.AUTH_USER_MODEL, verbose_name='customer account')),
            ],
            options={
                'verbose_name': 'WhatsApp conversation',
                'verbose_name_plural': 'WhatsApp conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='WhatsApp message id')),
                ('direction', models.CharField(choices=[('in', 'From customer'), ('out', 'From us')], max_length=3, verbose_name='direction')),
                ('msg_type', models.CharField(default='text', max_length=20, verbose_name='type')),
                ('body', models.TextField(blank=True, verbose_name='text')),
                ('media_id', models.CharField(blank=True, max_length=128, verbose_name='Meta media id')),
                ('media_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('E:/Navprana/private_media')), upload_to=whatsapp.models.media_upload_path, verbose_name='file')),
                ('media_mime', models.CharField(blank=True, max_length=100, verbose_name='file type')),
                ('media_filename', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('status', models.CharField(choices=[('received', 'Received'), ('pending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=12, verbose_name='status')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='time')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.conversation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='sent by')),
            ],
            options={
                'verbose_name': 'WhatsApp message',
                'verbose_name_plural': 'WhatsApp messages',
                'ordering': ['timestamp', 'pk'],
            },
        ),
    ]
