# Generated by Django 5.1.7 on 2025-09-30 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity of the product in the cart', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the cart was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the cart was last updated', verbose_name='Updated At')),
                ('products', models.ForeignKey(help_text='Products in the cart', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='product.product', verbose_name='Products')),
                ('user', models.ForeignKey(help_text='The user to whom this cart belongs', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-created_at'],
            },
        ),
    ]
