# Generated by Django 5.1.7 on 2026-01-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('product', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product in the cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='product.product', verbose_name='Product'),
        ),
    ]
