# Generated by Django 5.1.7 on 2025-09-30 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the order', max_length=20, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount of the order', max_digits=10, verbose_name='total amount')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the order', null=True, verbose_name='notes')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated discount amount from coupon', max_digits=10, verbose_name='discount amount')),
                ('payment_method', models.CharField(blank=True, max_length=255, verbose_name='payment method')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current payment status of the order', max_length=20, verbose_name='payment status')),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentage of tax to be applied', max_digits=5, null=True, verbose_name='tax percentage')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated tax amount', max_digits=10, verbose_name='tax amount')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final amount after discount and tax', max_digits=10, verbose_name='final amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('transaction_id', models.CharField(blank=True, help_text='Unique identifier for the payment transaction', max_length=255, null=True, unique=True, verbose_name='transaction ID')),
                ('coupon', models.ForeignKey(blank=True, help_text='Coupon applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupon.coupon', verbose_name='coupon')),
                ('user', models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product', verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product at time of order', max_digits=10, verbose_name='price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(help_text='Product being ordered', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
