# Generated by Django 5.1.7 on 2026-01-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, help_text='Generated invoice PDF for this order', null=True, upload_to='invoices/%Y/%m/', verbose_name='invoice'),
        ),
    ]
