# Generated by Django 5.1.7 on 2026-01-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total price for this item (price * quantity)', max_digits=10, verbose_name='total price'),
        ),
    ]
