# Generated by Django 5.1.7 on 2026-03-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cashfree', 'Cashfree'), ('cod', 'Cash on Delivery')], db_index=True, default='cashfree', help_text='Payment method selected for this order', max_length=20, verbose_name='payment method'),
        ),
    ]
