# Generated by Django 5.1.7 on 2026-03-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('netbanking', 'Net Banking'), ('card', 'Card Payment'), ('cod', 'Cash on Delivery')], db_index=True, default='upi', help_text='Payment method selected for this order', max_length=20, verbose_name='payment method'),
        ),
    ]
