# Generated by Django 5.1.7 on 2026-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='awb_number',
            field=models.CharField(blank=True, db_index=True, help_text='Tracking number printed on the shipping label', max_length=64, verbose_name='AWB / tracking number'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, choices=[('delhivery', 'Delhivery'), ('xpressbees', 'Xpressbees'), ('amazon_shipping', 'Amazon Shipping'), ('bluedart', 'Blue Dart'), ('dtdc', 'DTDC'), ('ecom_express', 'Ecom Express'), ('shadowfax', 'Shadowfax'), ('india_post', 'India Post'), ('other', 'Other')], help_text='Shipping partner carrying this order', max_length=32, verbose_name='courier'),
        ),
    ]
