# Generated by Django 5.1.7 on 2026-08-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_awb_number_order_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, choices=[('delhivery', 'Delhivery'), ('xpressbees', 'Xpressbees'), ('amazon_shipping', 'Amazon Shipping'), ('bluedart', 'Blue Dart'), ('dtdc', 'DTDC'), ('ecom_express', 'Ecom Express'), ('shadowfax', 'Shadowfax'), ('india_post', 'India Post')], help_text='Shipping partner carrying this order', max_length=32, verbose_name='courier'),
        ),
    ]
