# Generated by Django 5.1.7 on 2026-08-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping charge applied to this order', max_digits=10, verbose_name='shipping fee'),
        ),
    ]
