# Generated by Django 5.1.7 on 2026-09-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handling_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='COD handling fee charged on this order, as it stood when the order was placed', max_digits=10, verbose_name='handling fee'),
        ),
        migrations.AddField(
            model_name='order',
            name='prepaid_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount given for paying online, as it stood when the order was placed', max_digits=10, verbose_name='prepaid discount'),
        ),
    ]
